name: genomeview-binderized
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - cython
  - numpy
  - jupyterlab>=1.0
  - pip
  - pip:
    - git+https://github.com/nspies/genomeview.git
